<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Network_Monitor</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>appIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="appIcon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Network Monitor Library\Network Monitor Library.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ReaLTaiizor" Version="3.8.0.9" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.IO.Pipelines" Version="9.0.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="9.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>
</Project>